/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteCampaignsRouteImport } from './routes/_site.campaigns'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCsrRouteImport } from './routes/_site.csr'
import { Route as SiteDonateRouteImport } from './routes/_site.donate'
import { Route as SiteImpactRouteImport } from './routes/_site.impact'
import { Route as SitePartnerRouteImport } from './routes/_site.partner'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SiteRefundPolicyRouteImport } from './routes/_site.refund-policy'
import { Route as SiteStoriesRouteImport } from './routes/_site.stories'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as SiteTransparencyRouteImport } from './routes/_site.transparency'
import { Route as SiteVolunteerRouteImport } from './routes/_site.volunteer'
import { Route as SiteWorkRouteImport } from './routes/_site.work'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStoriesRouteImport } from './routes/admin.stories'
import { Route as AdminVolunteersRouteImport } from './routes/admin.volunteers'
import { Route as SiteAboutIndexRouteImport } from './routes/_site.about.index'
import { Route as SiteAboutFounderRouteImport } from './routes/_site.about.founder'
import { Route as SiteAboutGovernanceRouteImport } from './routes/_site.about.governance'
import { Route as SiteAboutVisionRouteImport } from './routes/_site.about.vision'
import { Route as SiteCampaignsIndexRouteImport } from './routes/_site.campaigns.index'
import { Route as SiteCampaignsSlugRouteImport } from './routes/_site.campaigns.$slug'
import { Route as SiteDonationFailedRouteImport } from './routes/_site.donation.failed'
import { Route as SiteDonationSuccessRouteImport } from './routes/_site.donation.success'
import { Route as SiteReceiptTokenRouteImport } from './routes/_site.receipt.$token'
import { Route as SiteStoriesIndexRouteImport } from './routes/_site.stories.index'
import { Route as SiteStoriesSlugRouteImport } from './routes/_site.stories.$slug'
import { Route as SiteTransparencyIndexRouteImport } from './routes/_site.transparency.index'
import { Route as SiteTransparencyRegistrationsRouteImport } from './routes/_site.transparency.registrations'
import { Route as SiteTransparencyReportsRouteImport } from './routes/_site.transparency.reports'
import { Route as SiteWorkIndexRouteImport } from './routes/_site.work.index'
import { Route as SiteWorkSlugRouteImport } from './routes/_site.work.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiReceiptsTokenRouteImport } from './routes/api/receipts/$token'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api/webhooks/razorpay'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCampaignsRoute = SiteCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCsrRoute = SiteCsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDonateRoute = SiteDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => SiteRoute,
} as any)
const SiteImpactRoute = SiteImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => SiteRoute,
} as any)
const SitePartnerRoute = SitePartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRefundPolicyRoute = SiteRefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStoriesRoute = SiteStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTransparencyRoute = SiteTransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => SiteRoute,
} as any)
const SiteVolunteerRoute = SiteVolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWorkRoute = SiteWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoriesRoute = AdminStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRoute,
} as any)
const SiteAboutIndexRoute = SiteAboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteAboutRoute,
} as any)
const SiteAboutFounderRoute = SiteAboutFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => SiteAboutRoute,
} as any)
const SiteAboutGovernanceRoute = SiteAboutGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => SiteAboutRoute,
} as any)
const SiteAboutVisionRoute = SiteAboutVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => SiteAboutRoute,
} as any)
const SiteCampaignsIndexRoute = SiteCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteCampaignsRoute,
} as any)
const SiteCampaignsSlugRoute = SiteCampaignsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteCampaignsRoute,
} as any)
const SiteDonationFailedRoute = SiteDonationFailedRouteImport.update({
  id: '/donation/failed',
  path: '/donation/failed',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDonationSuccessRoute = SiteDonationSuccessRouteImport.update({
  id: '/donation/success',
  path: '/donation/success',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReceiptTokenRoute = SiteReceiptTokenRouteImport.update({
  id: '/receipt/$token',
  path: '/receipt/$token',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStoriesIndexRoute = SiteStoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteStoriesRoute,
} as any)
const SiteStoriesSlugRoute = SiteStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteStoriesRoute,
} as any)
const SiteTransparencyIndexRoute = SiteTransparencyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteTransparencyRoute,
} as any)
const SiteTransparencyRegistrationsRoute =
  SiteTransparencyRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => SiteTransparencyRoute,
  } as any)
const SiteTransparencyReportsRoute = SiteTransparencyReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SiteTransparencyRoute,
} as any)
const SiteWorkIndexRoute = SiteWorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteWorkRoute,
} as any)
const SiteWorkSlugRoute = SiteWorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteWorkRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceiptsTokenRoute = ApiReceiptsTokenRouteImport.update({
  id: '/api/receipts/$token',
  path: '/api/receipts/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRouteWithChildren
  '/campaigns': typeof SiteCampaignsRouteWithChildren
  '/contact': typeof SiteContactRoute
  '/csr': typeof SiteCsrRoute
  '/donate': typeof SiteDonateRoute
  '/impact': typeof SiteImpactRoute
  '/partner': typeof SitePartnerRoute
  '/privacy': typeof SitePrivacyRoute
  '/refund-policy': typeof SiteRefundPolicyRoute
  '/stories': typeof SiteStoriesRouteWithChildren
  '/terms': typeof SiteTermsRoute
  '/transparency': typeof SiteTransparencyRouteWithChildren
  '/volunteer': typeof SiteVolunteerRoute
  '/work': typeof SiteWorkRouteWithChildren
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/': typeof AdminIndexRoute
  '/about/founder': typeof SiteAboutFounderRoute
  '/about/governance': typeof SiteAboutGovernanceRoute
  '/about/vision': typeof SiteAboutVisionRoute
  '/campaigns/$slug': typeof SiteCampaignsSlugRoute
  '/donation/failed': typeof SiteDonationFailedRoute
  '/donation/success': typeof SiteDonationSuccessRoute
  '/receipt/$token': typeof SiteReceiptTokenRoute
  '/stories/$slug': typeof SiteStoriesSlugRoute
  '/transparency/registrations': typeof SiteTransparencyRegistrationsRoute
  '/transparency/reports': typeof SiteTransparencyReportsRoute
  '/work/$slug': typeof SiteWorkSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/receipts/$token': typeof ApiReceiptsTokenRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/about/': typeof SiteAboutIndexRoute
  '/campaigns/': typeof SiteCampaignsIndexRoute
  '/stories/': typeof SiteStoriesIndexRoute
  '/transparency/': typeof SiteTransparencyIndexRoute
  '/work/': typeof SiteWorkIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contact': typeof SiteContactRoute
  '/csr': typeof SiteCsrRoute
  '/donate': typeof SiteDonateRoute
  '/impact': typeof SiteImpactRoute
  '/partner': typeof SitePartnerRoute
  '/privacy': typeof SitePrivacyRoute
  '/refund-policy': typeof SiteRefundPolicyRoute
  '/terms': typeof SiteTermsRoute
  '/volunteer': typeof SiteVolunteerRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/about/founder': typeof SiteAboutFounderRoute
  '/about/governance': typeof SiteAboutGovernanceRoute
  '/about/vision': typeof SiteAboutVisionRoute
  '/campaigns/$slug': typeof SiteCampaignsSlugRoute
  '/donation/failed': typeof SiteDonationFailedRoute
  '/donation/success': typeof SiteDonationSuccessRoute
  '/receipt/$token': typeof SiteReceiptTokenRoute
  '/stories/$slug': typeof SiteStoriesSlugRoute
  '/transparency/registrations': typeof SiteTransparencyRegistrationsRoute
  '/transparency/reports': typeof SiteTransparencyReportsRoute
  '/work/$slug': typeof SiteWorkSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/receipts/$token': typeof ApiReceiptsTokenRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/about': typeof SiteAboutIndexRoute
  '/campaigns': typeof SiteCampaignsIndexRoute
  '/stories': typeof SiteStoriesIndexRoute
  '/transparency': typeof SiteTransparencyIndexRoute
  '/work': typeof SiteWorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/about': typeof SiteAboutRouteWithChildren
  '/_site/campaigns': typeof SiteCampaignsRouteWithChildren
  '/_site/contact': typeof SiteContactRoute
  '/_site/csr': typeof SiteCsrRoute
  '/_site/donate': typeof SiteDonateRoute
  '/_site/impact': typeof SiteImpactRoute
  '/_site/partner': typeof SitePartnerRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/refund-policy': typeof SiteRefundPolicyRoute
  '/_site/stories': typeof SiteStoriesRouteWithChildren
  '/_site/terms': typeof SiteTermsRoute
  '/_site/transparency': typeof SiteTransparencyRouteWithChildren
  '/_site/volunteer': typeof SiteVolunteerRoute
  '/_site/work': typeof SiteWorkRouteWithChildren
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/about/founder': typeof SiteAboutFounderRoute
  '/_site/about/governance': typeof SiteAboutGovernanceRoute
  '/_site/about/vision': typeof SiteAboutVisionRoute
  '/_site/campaigns/$slug': typeof SiteCampaignsSlugRoute
  '/_site/donation/failed': typeof SiteDonationFailedRoute
  '/_site/donation/success': typeof SiteDonationSuccessRoute
  '/_site/receipt/$token': typeof SiteReceiptTokenRoute
  '/_site/stories/$slug': typeof SiteStoriesSlugRoute
  '/_site/transparency/registrations': typeof SiteTransparencyRegistrationsRoute
  '/_site/transparency/reports': typeof SiteTransparencyReportsRoute
  '/_site/work/$slug': typeof SiteWorkSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/receipts/$token': typeof ApiReceiptsTokenRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/_site/about/': typeof SiteAboutIndexRoute
  '/_site/campaigns/': typeof SiteCampaignsIndexRoute
  '/_site/stories/': typeof SiteStoriesIndexRoute
  '/_site/transparency/': typeof SiteTransparencyIndexRoute
  '/_site/work/': typeof SiteWorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/about'
    | '/campaigns'
    | '/contact'
    | '/csr'
    | '/donate'
    | '/impact'
    | '/partner'
    | '/privacy'
    | '/refund-policy'
    | '/stories'
    | '/terms'
    | '/transparency'
    | '/volunteer'
    | '/work'
    | '/admin/campaigns'
    | '/admin/content'
    | '/admin/documents'
    | '/admin/donations'
    | '/admin/enquiries'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/volunteers'
    | '/admin/'
    | '/about/founder'
    | '/about/governance'
    | '/about/vision'
    | '/campaigns/$slug'
    | '/donation/failed'
    | '/donation/success'
    | '/receipt/$token'
    | '/stories/$slug'
    | '/transparency/registrations'
    | '/transparency/reports'
    | '/work/$slug'
    | '/api/auth/$'
    | '/api/receipts/$token'
    | '/api/webhooks/razorpay'
    | '/about/'
    | '/campaigns/'
    | '/stories/'
    | '/transparency/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sitemap.xml'
    | '/contact'
    | '/csr'
    | '/donate'
    | '/impact'
    | '/partner'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/volunteer'
    | '/admin/campaigns'
    | '/admin/content'
    | '/admin/documents'
    | '/admin/donations'
    | '/admin/enquiries'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/volunteers'
    | '/'
    | '/admin'
    | '/about/founder'
    | '/about/governance'
    | '/about/vision'
    | '/campaigns/$slug'
    | '/donation/failed'
    | '/donation/success'
    | '/receipt/$token'
    | '/stories/$slug'
    | '/transparency/registrations'
    | '/transparency/reports'
    | '/work/$slug'
    | '/api/auth/$'
    | '/api/receipts/$token'
    | '/api/webhooks/razorpay'
    | '/about'
    | '/campaigns'
    | '/stories'
    | '/transparency'
    | '/work'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/_site/about'
    | '/_site/campaigns'
    | '/_site/contact'
    | '/_site/csr'
    | '/_site/donate'
    | '/_site/impact'
    | '/_site/partner'
    | '/_site/privacy'
    | '/_site/refund-policy'
    | '/_site/stories'
    | '/_site/terms'
    | '/_site/transparency'
    | '/_site/volunteer'
    | '/_site/work'
    | '/admin/campaigns'
    | '/admin/content'
    | '/admin/documents'
    | '/admin/donations'
    | '/admin/enquiries'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/volunteers'
    | '/_site/'
    | '/admin/'
    | '/_site/about/founder'
    | '/_site/about/governance'
    | '/_site/about/vision'
    | '/_site/campaigns/$slug'
    | '/_site/donation/failed'
    | '/_site/donation/success'
    | '/_site/receipt/$token'
    | '/_site/stories/$slug'
    | '/_site/transparency/registrations'
    | '/_site/transparency/reports'
    | '/_site/work/$slug'
    | '/api/auth/$'
    | '/api/receipts/$token'
    | '/api/webhooks/razorpay'
    | '/_site/about/'
    | '/_site/campaigns/'
    | '/_site/stories/'
    | '/_site/transparency/'
    | '/_site/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiReceiptsTokenRoute: typeof ApiReceiptsTokenRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/campaigns': {
      id: '/_site/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof SiteCampaignsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/csr': {
      id: '/_site/csr'
      path: '/csr'
      fullPath: '/csr'
      preLoaderRoute: typeof SiteCsrRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/donate': {
      id: '/_site/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof SiteDonateRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/impact': {
      id: '/_site/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof SiteImpactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/partner': {
      id: '/_site/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof SitePartnerRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/refund-policy': {
      id: '/_site/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof SiteRefundPolicyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/stories': {
      id: '/_site/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof SiteStoriesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/transparency': {
      id: '/_site/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof SiteTransparencyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/volunteer': {
      id: '/_site/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof SiteVolunteerRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/work': {
      id: '/_site/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof SiteWorkRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stories': {
      id: '/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AdminStoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/about/': {
      id: '/_site/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof SiteAboutIndexRouteImport
      parentRoute: typeof SiteAboutRoute
    }
    '/_site/about/founder': {
      id: '/_site/about/founder'
      path: '/founder'
      fullPath: '/about/founder'
      preLoaderRoute: typeof SiteAboutFounderRouteImport
      parentRoute: typeof SiteAboutRoute
    }
    '/_site/about/governance': {
      id: '/_site/about/governance'
      path: '/governance'
      fullPath: '/about/governance'
      preLoaderRoute: typeof SiteAboutGovernanceRouteImport
      parentRoute: typeof SiteAboutRoute
    }
    '/_site/about/vision': {
      id: '/_site/about/vision'
      path: '/vision'
      fullPath: '/about/vision'
      preLoaderRoute: typeof SiteAboutVisionRouteImport
      parentRoute: typeof SiteAboutRoute
    }
    '/_site/campaigns/': {
      id: '/_site/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof SiteCampaignsIndexRouteImport
      parentRoute: typeof SiteCampaignsRoute
    }
    '/_site/campaigns/$slug': {
      id: '/_site/campaigns/$slug'
      path: '/$slug'
      fullPath: '/campaigns/$slug'
      preLoaderRoute: typeof SiteCampaignsSlugRouteImport
      parentRoute: typeof SiteCampaignsRoute
    }
    '/_site/donation/failed': {
      id: '/_site/donation/failed'
      path: '/donation/failed'
      fullPath: '/donation/failed'
      preLoaderRoute: typeof SiteDonationFailedRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/donation/success': {
      id: '/_site/donation/success'
      path: '/donation/success'
      fullPath: '/donation/success'
      preLoaderRoute: typeof SiteDonationSuccessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/receipt/$token': {
      id: '/_site/receipt/$token'
      path: '/receipt/$token'
      fullPath: '/receipt/$token'
      preLoaderRoute: typeof SiteReceiptTokenRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/stories/': {
      id: '/_site/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof SiteStoriesIndexRouteImport
      parentRoute: typeof SiteStoriesRoute
    }
    '/_site/stories/$slug': {
      id: '/_site/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof SiteStoriesSlugRouteImport
      parentRoute: typeof SiteStoriesRoute
    }
    '/_site/transparency/': {
      id: '/_site/transparency/'
      path: '/'
      fullPath: '/transparency/'
      preLoaderRoute: typeof SiteTransparencyIndexRouteImport
      parentRoute: typeof SiteTransparencyRoute
    }
    '/_site/transparency/registrations': {
      id: '/_site/transparency/registrations'
      path: '/registrations'
      fullPath: '/transparency/registrations'
      preLoaderRoute: typeof SiteTransparencyRegistrationsRouteImport
      parentRoute: typeof SiteTransparencyRoute
    }
    '/_site/transparency/reports': {
      id: '/_site/transparency/reports'
      path: '/reports'
      fullPath: '/transparency/reports'
      preLoaderRoute: typeof SiteTransparencyReportsRouteImport
      parentRoute: typeof SiteTransparencyRoute
    }
    '/_site/work/': {
      id: '/_site/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof SiteWorkIndexRouteImport
      parentRoute: typeof SiteWorkRoute
    }
    '/_site/work/$slug': {
      id: '/_site/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof SiteWorkSlugRouteImport
      parentRoute: typeof SiteWorkRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receipts/$token': {
      id: '/api/receipts/$token'
      path: '/api/receipts/$token'
      fullPath: '/api/receipts/$token'
      preLoaderRoute: typeof ApiReceiptsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteAboutRouteChildren {
  SiteAboutFounderRoute: typeof SiteAboutFounderRoute
  SiteAboutGovernanceRoute: typeof SiteAboutGovernanceRoute
  SiteAboutVisionRoute: typeof SiteAboutVisionRoute
  SiteAboutIndexRoute: typeof SiteAboutIndexRoute
}

const SiteAboutRouteChildren: SiteAboutRouteChildren = {
  SiteAboutFounderRoute: SiteAboutFounderRoute,
  SiteAboutGovernanceRoute: SiteAboutGovernanceRoute,
  SiteAboutVisionRoute: SiteAboutVisionRoute,
  SiteAboutIndexRoute: SiteAboutIndexRoute,
}

const SiteAboutRouteWithChildren = SiteAboutRoute._addFileChildren(
  SiteAboutRouteChildren,
)

interface SiteCampaignsRouteChildren {
  SiteCampaignsSlugRoute: typeof SiteCampaignsSlugRoute
  SiteCampaignsIndexRoute: typeof SiteCampaignsIndexRoute
}

const SiteCampaignsRouteChildren: SiteCampaignsRouteChildren = {
  SiteCampaignsSlugRoute: SiteCampaignsSlugRoute,
  SiteCampaignsIndexRoute: SiteCampaignsIndexRoute,
}

const SiteCampaignsRouteWithChildren = SiteCampaignsRoute._addFileChildren(
  SiteCampaignsRouteChildren,
)

interface SiteStoriesRouteChildren {
  SiteStoriesSlugRoute: typeof SiteStoriesSlugRoute
  SiteStoriesIndexRoute: typeof SiteStoriesIndexRoute
}

const SiteStoriesRouteChildren: SiteStoriesRouteChildren = {
  SiteStoriesSlugRoute: SiteStoriesSlugRoute,
  SiteStoriesIndexRoute: SiteStoriesIndexRoute,
}

const SiteStoriesRouteWithChildren = SiteStoriesRoute._addFileChildren(
  SiteStoriesRouteChildren,
)

interface SiteTransparencyRouteChildren {
  SiteTransparencyRegistrationsRoute: typeof SiteTransparencyRegistrationsRoute
  SiteTransparencyReportsRoute: typeof SiteTransparencyReportsRoute
  SiteTransparencyIndexRoute: typeof SiteTransparencyIndexRoute
}

const SiteTransparencyRouteChildren: SiteTransparencyRouteChildren = {
  SiteTransparencyRegistrationsRoute: SiteTransparencyRegistrationsRoute,
  SiteTransparencyReportsRoute: SiteTransparencyReportsRoute,
  SiteTransparencyIndexRoute: SiteTransparencyIndexRoute,
}

const SiteTransparencyRouteWithChildren =
  SiteTransparencyRoute._addFileChildren(SiteTransparencyRouteChildren)

interface SiteWorkRouteChildren {
  SiteWorkSlugRoute: typeof SiteWorkSlugRoute
  SiteWorkIndexRoute: typeof SiteWorkIndexRoute
}

const SiteWorkRouteChildren: SiteWorkRouteChildren = {
  SiteWorkSlugRoute: SiteWorkSlugRoute,
  SiteWorkIndexRoute: SiteWorkIndexRoute,
}

const SiteWorkRouteWithChildren = SiteWorkRoute._addFileChildren(
  SiteWorkRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRouteWithChildren
  SiteCampaignsRoute: typeof SiteCampaignsRouteWithChildren
  SiteContactRoute: typeof SiteContactRoute
  SiteCsrRoute: typeof SiteCsrRoute
  SiteDonateRoute: typeof SiteDonateRoute
  SiteImpactRoute: typeof SiteImpactRoute
  SitePartnerRoute: typeof SitePartnerRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteRefundPolicyRoute: typeof SiteRefundPolicyRoute
  SiteStoriesRoute: typeof SiteStoriesRouteWithChildren
  SiteTermsRoute: typeof SiteTermsRoute
  SiteTransparencyRoute: typeof SiteTransparencyRouteWithChildren
  SiteVolunteerRoute: typeof SiteVolunteerRoute
  SiteWorkRoute: typeof SiteWorkRouteWithChildren
  SiteIndexRoute: typeof SiteIndexRoute
  SiteDonationFailedRoute: typeof SiteDonationFailedRoute
  SiteDonationSuccessRoute: typeof SiteDonationSuccessRoute
  SiteReceiptTokenRoute: typeof SiteReceiptTokenRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRouteWithChildren,
  SiteCampaignsRoute: SiteCampaignsRouteWithChildren,
  SiteContactRoute: SiteContactRoute,
  SiteCsrRoute: SiteCsrRoute,
  SiteDonateRoute: SiteDonateRoute,
  SiteImpactRoute: SiteImpactRoute,
  SitePartnerRoute: SitePartnerRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteRefundPolicyRoute: SiteRefundPolicyRoute,
  SiteStoriesRoute: SiteStoriesRouteWithChildren,
  SiteTermsRoute: SiteTermsRoute,
  SiteTransparencyRoute: SiteTransparencyRouteWithChildren,
  SiteVolunteerRoute: SiteVolunteerRoute,
  SiteWorkRoute: SiteWorkRouteWithChildren,
  SiteIndexRoute: SiteIndexRoute,
  SiteDonationFailedRoute: SiteDonationFailedRoute,
  SiteDonationSuccessRoute: SiteDonationSuccessRoute,
  SiteReceiptTokenRoute: SiteReceiptTokenRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoriesRoute: typeof AdminStoriesRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoriesRoute: AdminStoriesRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiReceiptsTokenRoute: ApiReceiptsTokenRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
